-- Cita Perfecta - Supabase schema completo
-- Ejecuta este archivo en Supabase > SQL Editor.

create extension if not exists "pgcrypto";

-- =========================================================
-- Helpers
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =========================================================
-- Profiles
-- =========================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  username text unique,
  birth_date date,
  age int,
  city text,
  bio text,
  photo_url text,
  interests text[] not null default '{}',
  traits text[] not null default '{}',
  communication_style text,
  love_language text,
  dealbreakers text[] not null default '{}',
  pact_accepted boolean not null default false,
  is_onboarded boolean not null default false,
  profile_complete boolean not null default false,
  test_complete boolean not null default false,
  pause_mode boolean not null default false,
  premium boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
add column if not exists is_onboarded boolean not null default false;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    email,
    full_name,
    birth_date,
    age
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    nullif(new.raw_user_meta_data ->> 'birthDate', '')::date,
    nullif(new.raw_user_meta_data ->> 'age', '')::int
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- =========================================================
-- Questions
-- =========================================================

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  text text not null,
  category text not null,
  weight int not null default 1,
  is_initial boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.questions
add column if not exists is_initial boolean not null default true;

insert into public.questions (id, text, category, weight, is_initial, is_active)
values
  (1, 'Me gusta hablar con claridad cuando algo me incomoda.', 'comunicacion', 2, true, true),
  (2, 'Busco una relacion tranquila, honesta y con respeto.', 'valores', 2, true, true),
  (3, 'Prefiero planes tranquilos antes que salir de fiesta todo el tiempo.', 'estilo', 1, true, true),
  (4, 'Para mi es importante tener metas personales claras.', 'metas', 2, true, true),
  (5, 'Me gusta conocer a alguien con calma, sin presiones.', 'valores', 2, true, true),
  (6, 'Disfruto conversaciones profundas sobre la vida y emociones.', 'comunicacion', 1, true, true),
  (7, 'Valoro mucho el tiempo de calidad.', 'valores', 2, true, true),
  (8, 'Me gusta compartir gustos como musica, peliculas o tecnologia.', 'intereses', 1, true, true),
  (9, 'Cuando algo termina, prefiero cerrar con respeto y claridad.', 'comunicacion', 2, true, true),
  (10, 'Me interesa una conexion real, no solo una coincidencia rapida.', 'metas', 2, true, true)
on conflict (id) do update set
  text = excluded.text,
  category = excluded.category,
  weight = excluded.weight,
  is_initial = excluded.is_initial,
  is_active = excluded.is_active;

select setval(
  pg_get_serial_sequence('public.questions', 'id'),
  greatest((select coalesce(max(id), 1) from public.questions), 1),
  true
);

-- =========================================================
-- Answers
-- =========================================================

create table if not exists public.answers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  value int not null check (value between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, question_id)
);

drop trigger if exists answers_set_updated_at on public.answers;
create trigger answers_set_updated_at
before update on public.answers
for each row execute function public.set_updated_at();

-- =========================================================
-- Swipes
-- =========================================================

create table if not exists public.swipes (
  id uuid primary key default gen_random_uuid(),
  from_user_id uuid not null references public.profiles(id) on delete cascade,
  to_user_id uuid not null references public.profiles(id) on delete cascade,
  action text not null check (action in ('like', 'pass')),
  comment text,
  created_at timestamptz not null default now(),
  unique (from_user_id, to_user_id),
  check (from_user_id <> to_user_id)
);

-- =========================================================
-- Matches
-- =========================================================

create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  compatibility int not null default 80 check (compatibility between 0 and 100),
  status text not null default 'active' check (status in ('active', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_a, user_b),
  check (user_a <> user_b)
);

drop trigger if exists matches_set_updated_at on public.matches;
create trigger matches_set_updated_at
before update on public.matches
for each row execute function public.set_updated_at();

create or replace function public.create_match_on_mutual_like()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.action = 'like' and exists (
    select 1
    from public.swipes
    where from_user_id = new.to_user_id
      and to_user_id = new.from_user_id
      and action = 'like'
  ) then
    insert into public.matches (user_a, user_b)
    values (
      least(new.from_user_id, new.to_user_id),
      greatest(new.from_user_id, new.to_user_id)
    )
    on conflict (user_a, user_b) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists swipes_create_match on public.swipes;
create trigger swipes_create_match
after insert on public.swipes
for each row execute function public.create_match_on_mutual_like();

-- =========================================================
-- Chats
-- =========================================================

create table if not exists public.chats (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches(id) on delete cascade,
  status text not null default 'active' check (status in ('active', 'closed')),
  close_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id)
);

drop trigger if exists chats_set_updated_at on public.chats;
create trigger chats_set_updated_at
before update on public.chats
for each row execute function public.set_updated_at();

-- =========================================================
-- Messages
-- =========================================================

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.chats(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

-- =========================================================
-- Connection letters
-- =========================================================

create table if not exists public.connection_letters (
  id uuid primary key default gen_random_uuid(),
  from_user_id uuid not null references public.profiles(id) on delete cascade,
  to_user_id uuid not null references public.profiles(id) on delete cascade,
  message text not null,
  status text not null default 'sent' check (status in ('sent', 'read', 'accepted', 'rejected')),
  created_at timestamptz not null default now(),
  check (from_user_id <> to_user_id)
);

-- =========================================================
-- Reports
-- =========================================================

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reported_user_id uuid not null references public.profiles(id) on delete cascade,
  reason text not null,
  description text,
  status text not null default 'pending' check (status in ('pending', 'reviewed', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  check (reporter_id <> reported_user_id)
);

-- =========================================================
-- Blocks
-- =========================================================

create table if not exists public.blocks (
  id uuid primary key default gen_random_uuid(),
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (blocker_id, blocked_user_id),
  check (blocker_id <> blocked_user_id)
);

-- =========================================================
-- Indexes
-- =========================================================

create index if not exists profiles_city_idx on public.profiles(city);
create index if not exists answers_user_id_idx on public.answers(user_id);
create index if not exists swipes_from_user_id_idx on public.swipes(from_user_id);
create index if not exists swipes_to_user_id_idx on public.swipes(to_user_id);
create index if not exists matches_user_a_idx on public.matches(user_a);
create index if not exists matches_user_b_idx on public.matches(user_b);
create index if not exists chats_match_id_idx on public.chats(match_id);
create index if not exists messages_chat_id_created_at_idx on public.messages(chat_id, created_at);
create index if not exists letters_from_user_id_idx on public.connection_letters(from_user_id);
create index if not exists letters_to_user_id_idx on public.connection_letters(to_user_id);
create index if not exists reports_reporter_id_idx on public.reports(reporter_id);
create index if not exists reports_reported_user_id_idx on public.reports(reported_user_id);
create index if not exists blocks_blocker_id_idx on public.blocks(blocker_id);
create index if not exists blocks_blocked_user_id_idx on public.blocks(blocked_user_id);

-- =========================================================
-- RLS
-- =========================================================

alter table public.profiles enable row level security;
alter table public.questions enable row level security;
alter table public.answers enable row level security;
alter table public.swipes enable row level security;
alter table public.matches enable row level security;
alter table public.chats enable row level security;
alter table public.messages enable row level security;
alter table public.connection_letters enable row level security;
alter table public.reports enable row level security;
alter table public.blocks enable row level security;

-- Profiles
drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles
for select
to authenticated
using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Questions
drop policy if exists "questions_select_authenticated" on public.questions;
create policy "questions_select_authenticated"
on public.questions
for select
to authenticated
using (is_active = true);

-- Answers
drop policy if exists "answers_manage_own" on public.answers;
create policy "answers_manage_own"
on public.answers
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Swipes
drop policy if exists "swipes_insert_own" on public.swipes;
create policy "swipes_insert_own"
on public.swipes
for insert
to authenticated
with check (auth.uid() = from_user_id);

drop policy if exists "swipes_select_related" on public.swipes;
create policy "swipes_select_related"
on public.swipes
for select
to authenticated
using (auth.uid() = from_user_id or auth.uid() = to_user_id);

-- Matches
drop policy if exists "matches_select_own" on public.matches;
create policy "matches_select_own"
on public.matches
for select
to authenticated
using (auth.uid() = user_a or auth.uid() = user_b);

drop policy if exists "matches_update_own" on public.matches;
create policy "matches_update_own"
on public.matches
for update
to authenticated
using (auth.uid() = user_a or auth.uid() = user_b)
with check (auth.uid() = user_a or auth.uid() = user_b);

-- Chats
drop policy if exists "chats_select_own" on public.chats;
create policy "chats_select_own"
on public.chats
for select
to authenticated
using (
  exists (
    select 1 from public.matches
    where matches.id = chats.match_id
      and (matches.user_a = auth.uid() or matches.user_b = auth.uid())
  )
);

drop policy if exists "chats_insert_own_match" on public.chats;
create policy "chats_insert_own_match"
on public.chats
for insert
to authenticated
with check (
  exists (
    select 1 from public.matches
    where matches.id = chats.match_id
      and (matches.user_a = auth.uid() or matches.user_b = auth.uid())
  )
);

drop policy if exists "chats_update_own" on public.chats;
create policy "chats_update_own"
on public.chats
for update
to authenticated
using (
  exists (
    select 1 from public.matches
    where matches.id = chats.match_id
      and (matches.user_a = auth.uid() or matches.user_b = auth.uid())
  )
)
with check (
  exists (
    select 1 from public.matches
    where matches.id = chats.match_id
      and (matches.user_a = auth.uid() or matches.user_b = auth.uid())
  )
);

-- Messages
drop policy if exists "messages_select_own_chat" on public.messages;
create policy "messages_select_own_chat"
on public.messages
for select
to authenticated
using (
  exists (
    select 1
    from public.chats
    join public.matches on matches.id = chats.match_id
    where chats.id = messages.chat_id
      and (matches.user_a = auth.uid() or matches.user_b = auth.uid())
  )
);

drop policy if exists "messages_insert_own_chat" on public.messages;
create policy "messages_insert_own_chat"
on public.messages
for insert
to authenticated
with check (
  auth.uid() = sender_id
  and exists (
    select 1
    from public.chats
    join public.matches on matches.id = chats.match_id
    where chats.id = messages.chat_id
      and (matches.user_a = auth.uid() or matches.user_b = auth.uid())
  )
);

-- Connection letters
drop policy if exists "letters_insert_own" on public.connection_letters;
create policy "letters_insert_own"
on public.connection_letters
for insert
to authenticated
with check (auth.uid() = from_user_id);

drop policy if exists "letters_select_related" on public.connection_letters;
create policy "letters_select_related"
on public.connection_letters
for select
to authenticated
using (auth.uid() = from_user_id or auth.uid() = to_user_id);

drop policy if exists "letters_update_receiver" on public.connection_letters;
create policy "letters_update_receiver"
on public.connection_letters
for update
to authenticated
using (auth.uid() = to_user_id)
with check (auth.uid() = to_user_id);

-- Reports
drop policy if exists "reports_insert_own" on public.reports;
create policy "reports_insert_own"
on public.reports
for insert
to authenticated
with check (auth.uid() = reporter_id);

drop policy if exists "reports_select_own" on public.reports;
create policy "reports_select_own"
on public.reports
for select
to authenticated
using (auth.uid() = reporter_id);

-- Blocks
drop policy if exists "blocks_manage_own" on public.blocks;
create policy "blocks_manage_own"
on public.blocks
for all
to authenticated
using (auth.uid() = blocker_id)
with check (auth.uid() = blocker_id);
